In [1]:
%matplotlib inline
import seaborn as sns
import os
import sys
import subprocess
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from pyarrow import fs
import pyarrow.parquet as pq
import pandas as pd
import numpy as np

os.environ["HADOOP_CONF_DIR"] = "/path/to/hadoop/conf/"
os.environ["JAVA_HOME"] = "/path/to/java"
os.environ["HADOOP_HOME"] = "/path/to/hadoop"
os.environ["ARROW_LIBHDFS_DIR"] = "/path/to/hadoop/lib/"
os.environ["CLASSPATH"] = subprocess.check_output(
    "$HADOOP_HOME/bin/hadoop classpath --glob", shell=True
).decode("utf-8")

hdfs = fs.HadoopFileSystem(
    host="hdfs://your-hdfs-host", port=8020
)

from tqdm import tqdm
import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning

warnings.simplefilter('ignore', ConvergenceWarning)
import sys

if not sys.warnoptions:
    import warnings

    warnings.simplefilter("ignore")

import logging

logging.getLogger("prophet").setLevel(logging.WARNING)
logging.getLogger("cmdstanpy").disabled = True

df_total = pd.read_parquet(
    "/path/to/company_data/sa/cpc/store/data/SUM_TOTAL/total_sl_13_provinces_2024-07.parquet",
    filesystem=hdfs, )
df_total.sort_index(ascending=False).head()
# df_total = df_total[df_total.index<'2023-7-1']

2024-08-12 16:48:52,803 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

,PHIEN,BDINH,DANANG,DLAC,DNONG,GLAI,KHOA,KTUM,PYEN,QBINH,QNAM,QNGAI,QTRI,TTHUE,TOTAL
42,2024-07-01,255772368,359420497,175574535,51863903,101472322,288388568,37254149,105210301,115404015,256516607,219072794,82544968,201949922,2250444949
41,2024-06-01,260833989,370651778,192202350,58677511,122640070,287084140,41322242,105866124,122718500,261090273,231255978,84618179,209714426,2348675560
40,2024-05-01,260856946,338171599,222915053,69759755,132602652,287016154,43327721,106753144,107833547,260995710,238125119,79620384,197414563,2345392347
39,2024-04-01,244363691,308628213,254755130,76584240,166302227,263096083,49888676,101403567,104588279,233382499,221977075,72590240,186712681,2284272601
38,2024-03-01,226434785,284965616,255725535,79694103,160766425,235694577,53305738,91294032,86277063,218984921,195208922,65839829,163365520,2117557066

In [2]:
pd.read_parquet('/path/to/company_data/user/<user>/cpc/data/parameter/final_params_13province_u2023.parquet',filesystem=hdfs)

,province,n_max,lag,type_decomp,method_season,method_resid,method_trend,error_abs
0,BDINH,10,6,STL,statistics,None,average,0.081362
1,DANANG,10,6,STL,statistics,arima,average,0.066686
2,DLAC,10,6,STL,statistics,arima,average,0.198305
3,DNONG,5,6,STL,statistics,arima,average,0.246375
4,GLAI,5,8,STL,statistics,None,average,0.144923
5,KHOA,5,6,STL,statistics,arima,average,0.089738
6,KTUM,2,10,STL,statistics,None,average,0.128623
7,PYEN,5,6,STL,statistics,None,average,0.144254
8,QBINH,2,8,STL,statistics,None,average,0.141760
9,QNAM,10,6,STL,statistics,arima,average,0.066424
10,QNGAI,10,6,STL,statistics,arima,average,0.101527
11,QTRI,5,8,STL,statistics,None,average,0.130764
12,TTHUE,10,10,STL,statistics,None,average,0.058410

In [7]:
df_total

,PHIEN,BDINH,DANANG,DLAC,DNONG,GLAI,KHOA,KTUM,PYEN,QBINH,QNAM,QNGAI,QTRI,TTHUE,TOTAL
0,2021-01-01,172740120,203601803,147457074,44596327,90428875,154108940,41738931,64427738,75663066,157055696,174093766,54194223,128704328,1508810887
1,2021-02-01,144247290,180774297,147913340,48214165,106511589,146572064,34211284,62135056,72019515,140222204,150764661,48705202,117046364,1399337031
2,2021-03-01,181550824,194145612,186440175,48782238,108250474,152211725,38802307,70020661,73264978,154367593,159436181,50696210,129905222,1547874200
3,2021-04-01,199746953,238971267,206295423,52172946,124368219,192014064,37639153,84095864,85638321,192248075,183784444,58072285,149330895,1804377909
4,2021-05-01,204394644,245267546,176763006,43851699,100472859,197897822,32011523,86273178,88530983,196539440,183387482,61960664,161610697,1778961543
5,2021-06-01,228505885,266731131,142944656,46174071,101666699,211777539,33170708,92921191,107204687,217478486,218354068,71719111,178211205,1916859437
6,2021-07-01,221138117,270969071,151337167,41506884,91817473,198623691,32665248,85375068,105889038,220382599,208500094,71489061,176280231,1875973742
7,2021-08-01,219844509,261542900,138773834,42523878,87648926,195990592,36277376,89138509,107068894,217134381,244827558,71962232,184218767,1896952356
8,2021-09-01,198720930,215147407,143631179,44390920,91234608,177671416,39612071,85693213,92221686,191223040,184386773,68179220,162030947,1694143410
9,2021-10-01,195872288,214121072,145116628,38845340,88811751,173821507,37360942,80852684,82113117,185683049,185432814,62444370,150443703,1640919265
10,2021-11-01,195535051,217400617,147689950,44586510,93469521,177562948,40115118,76704600,81841121,183965811,181066575,58789117,145297494,1644024433
11,2021-12-01,173441716,198994259,143334763,49515931,97229769,158120587,40396961,67493171,77617610,172347874,184809368,56830182,143496539,1563628730
12,2022-01-01,173902081,200844040,159215340,50934810,98923830,166973297,39487525,69983116,79172261,183041258,185728043,55992092,139153276,1603350969
13,2022-02-01,169243045,183664073,178768506,50882748,114627203,165854520,36915981,72015636,75402829,170326406,164689463,57336436,133888101,1573614947
14,2022-03-01,184695751,196660177,186786924,47098103,118909097,166021168,41039215,71087858,74698558,175430145,159380947,53792590,144545277,1620145810
15,2022-04-01,199531458,232943210,179595494,47854612,115090499,199216837,39204308,83477911,87063045,200294158,180048001,60852371,155510497,1780682401
16,2022-05-01,205846346,243426759,152399328,44089913,98650890,207994288,33678006,83125885,89004131,203024065,197271984,61077304,162018217,1781607116
17,2022-06-01,225268513,296453092,151675736,45821674,98692154,238037275,33947047,93075247,105254582,223875686,186703797,70382710,185350014,1954537527
18,2022-07-01,223975070,302114730,150479215,42659220,98949287,236142364,33915240,92196207,109751551,233445367,195254898,74152874,188618574,1981654597
19,2022-08-01,219324309,303756047,148577723,45362393,96345256,227484949,38573831,91424519,110158224,231672958,200712772,74462738,189314786,1977170505
20,2022-09-01,220282463,298237762,169487049,55881942,106842652,224916166,42608718,93645587,105335207,219048697,198447610,74902017,173862340,1983498210
21,2022-10-01,205319852,278077938,144978237,51064158,102127134,216477350,40959586,81639051,89388406,197378689,178195641,67843691,152247198,1805696931
22,2022-11-01,193892466,238387870,152173396,56085317,103967415,202819821,42452820,82232417,78317781,200954983,186224647,60735187,164861048,1763105168
23,2022-12-01,188953287,238237420,160250539,54946562,106903956,186773918,46003139,74328607,82149136,194672756,177555622,60516914,148838468,1720130324
24,2023-01-01,151278934,198020079,146805744,53889420,105304740,175314182,37165631,65447813,69787181,159478872,152550110,52299987,124931855,1492274548
25,2023-02-01,177961166,214893731,181171306,56540322,127792773,189924549,44341187,75307632,78307702,182058583,176091725,60878115,143340887,1708609678
26,2023-03-01,176867768,226760150,203365421,66022917,128334530,184065794,43121854,70803450,78504209,187505156,160738906,55776102,145886111,1727752368
27,2023-04-01,201071762,263577819,199440776,65812059,130184998,227387246,41138185,86218995,87052560,207999642,171806536,63538594,171897527,1917126699
28,2023-05-01,216810167,286065814,187296839,60365365,117478037,247775311,38476870,92239501,94808312,218040740,200881892,66616139,175082939,2001937926
29,2023-06-01,228831703,330679786,168895712,53361487,107430058,271527719,36919148,96108003,110711603,227748124,195321222,76746089,195194018,2099474672
30,2023-07-01,233239947,326930522,157939171,53774306,99639058,257318544,35575725,98089406,113635119,235583294,208659512,76274477,198860925,2095520006
31,2023-08-01,242371738,343783477,163510885,56349981,102942041,265621102,41849276,102249857,110559224,240644513,215322023,76426513,199147336,2160777966
32,2023-09-01,245846739,334854205,176154962,54350765,110230293,260440322,43585903,100944943,99008566,236540705,205012048,77915611,178232208,2123117270
33,2023-10-01,229283628,325046776,177891988,55271575,104950394,268993300,45397486,107902396,89358961,216527628,191251580,69936919,174538640,2056351271
34,2023-11-01,237220530,306060760,181575737,65081029,123236212,245231088,46903748,81903276,92552312,225265298,188298784,78325276,166285061,2037939111
35,2023-12-01,209589687,251941410,192772258,68487295,129279584,220393105,53503395,91446014,76917535,198279228,177979839,69479002,168910328,1908978680
36,2024-01-01,217752375,245424572,187220071,76774275,175083206,209372461,52703106,80418680,89993245,230284016,174027218,60340117,143831781,1943225123
37,2024-02-01,192574920,207447504,197532396,70362781,146878983,196068026,42041468,75196236,70169936,169600044,161678291,55613670,127720682,1712884937
38,2024-03-01,226434785,284965616,255725535,79694103,160766425,235694577,53305738,91294032,86277063,218984921,195208922,65839829,163365520,2117557066
39,2024-04-01,244363691,308628213,254755130,76584240,166302227,263096083,49888676,101403567,104588279,233382499,221977075,72590240,186712681,2284272601
40,2024-05-01,260856946,338171599,222915053,69759755,132602652,287016154,43327721,106753144,107833547,260995710,238125119,79620384,197414563,2345392347
41,2024-06-01,260833989,370651778,192202350,58677511,122640070,287084140,41322242,105866124,122718500,261090273,231255978,84618179,209714426,2348675560
42,2024-07-01,255772368,340755894,175574535,51863903,101472322,287274057,37254149,105210301,115404015,256516607,219072794,82544968,201949922,2230665835

In [2]:
df_profile = pd.read_parquet(
    "/path/to/company_data/user/<user>/CPC/profile_CPC",
    filesystem=hdfs, )
df_code = pd.read_parquet('/path/to/company_data/sa/cpc/store/data/SUM_TOTAL/df_dvi.parquet',filesystem=hdfs)

df_sl_13province = pd.DataFrame()
for year in range(2014,2025):
    df_each_year = pd.read_parquet("/path/to/company_data/user/<user>/CPC/SL_MDD_1M.parquet/Y={}".format(year),
                                   filesystem=hdfs)
    df_each_year['year'] = year
    print(df_each_year.shape)
    df_sl_13province = pd.concat([df_sl_13province,df_each_year],axis=0)
    # break
df_sl_13province['date'] = df_sl_13province.apply(lambda row: f"{row['year']}-{row['M']}-1",axis=1)
df_sl_13province['date'] = pd.to_datetime(df_sl_13province['date'])

df_total = df_sl_13province.merge(df_profile[['MA_DDO','U']],on='MA_DDO',how='left')
df_code.columns = ['PROVINCE', 'U', 'DVI_VN', 'DVI_FULL', 'UPDATE_DATE']
df_total = df_total.merge(df_code[['U','PROVINCE']],on='U',how='left')
df_total = df_total.drop(8342)
df_total = df_total[df_total['SLUONG_FINAL'] > 0]

(9307, 13)
(10498, 13)
(11900, 13)
(13273, 13)
(14744, 13)
(16408, 13)
(17825, 13)
(18868, 13)
(19212, 13)
(20076, 13)
(1666, 13)

NameError: name 'df_profile' is not defined

In [3]:
df_sl_13province

,MA_KHANG,MA_DDO,SO_CTO,HS_NHAN,NGAY_DKY,NGAY_CKY,DELTA_DAYS,SAN_LUONG,SLUONG_TTIEP,SLUONG_TRPHU,SLUONG_FINAL,M,year,date
0,PC01AA0108011,PC01AA0108011001,11143494,150,2013-12-24,2014-01-20,28.0,36652.0,0.0,1230.0,35422,1,2014,2014-01-01
1,PC01AA0108230,PC01AA0108230001,00036621,100,2013-12-26,2014-01-25,31.0,84470.0,0.0,0.0,84470,1,2014,2014-01-01
2,PC01AA0109823,PC01AA0109823001,13102149,300,2013-12-26,2014-01-25,31.0,195324.0,0.0,0.0,195324,1,2014,2014-01-01
3,PC01AA0119496,PC01AA0119496001,10089402,30,2013-12-24,2014-01-20,28.0,29395.0,0.0,0.0,29395,1,2014,2014-01-01
4,PC01AA0120335,PC01AA0120335001,08003433,80,2013-12-26,2014-01-25,31.0,32550.0,0.0,0.0,32550,1,2014,2014-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661,PC13HH0709259,PC13HH0709259001,17080923,320,2024-01-01,2024-01-31,31.0,113818.0,0.0,0.0,113818,1,2024,2024-01-01
1662,PC13II0608847,PC13II0608847001,19025021,160,2024-01-01,2024-01-31,31.0,44440.0,0.0,0.0,44440,1,2024,2024-01-01
1663,PC13II0715667,PC13II0715667001,20029041,40,2024-01-01,2024-01-31,31.0,6583.0,0.0,0.0,6583,1,2024,2024-01-01
1664,PC13II0718026,PC13II0718026001,21040524,80,2024-01-01,2024-01-31,31.0,85319.0,0.0,0.0,85319,1,2024,2024-01-01
1665,PC13II0718258,PC13II0718258001,21040558,1600,2024-01-01,2024-01-31,31.0,1184.0,0.0,0.0,1184,1,2024,2024-01-01

In [9]:
df_total

,PHIEN,BDINH,DANANG,DLAC,DNONG,GLAI,KHOA,KTUM,PYEN,QBINH,QNAM,QNGAI,QTRI,TTHUE,TOTAL
0,2021-01-01,172740120,203601803,147457074,44596327,90428875,154108940,41738931,64427738,75663066,157055696,174093766,54194223,128704328,1508810887
1,2021-02-01,144247290,180774297,147913340,48214165,106511589,146572064,34211284,62135056,72019515,140222204,150764661,48705202,117046364,1399337031
2,2021-03-01,181550824,194145612,186440175,48782238,108250474,152211725,38802307,70020661,73264978,154367593,159436181,50696210,129905222,1547874200
3,2021-04-01,199746953,238971267,206295423,52172946,124368219,192014064,37639153,84095864,85638321,192248075,183784444,58072285,149330895,1804377909
4,2021-05-01,204394644,245267546,176763006,43851699,100472859,197897822,32011523,86273178,88530983,196539440,183387482,61960664,161610697,1778961543
5,2021-06-01,228505885,266731131,142944656,46174071,101666699,211777539,33170708,92921191,107204687,217478486,218354068,71719111,178211205,1916859437
6,2021-07-01,221138117,270969071,151337167,41506884,91817473,198623691,32665248,85375068,105889038,220382599,208500094,71489061,176280231,1875973742
7,2021-08-01,219844509,261542900,138773834,42523878,87648926,195990592,36277376,89138509,107068894,217134381,244827558,71962232,184218767,1896952356
8,2021-09-01,198720930,215147407,143631179,44390920,91234608,177671416,39612071,85693213,92221686,191223040,184386773,68179220,162030947,1694143410
9,2021-10-01,195872288,214121072,145116628,38845340,88811751,173821507,37360942,80852684,82113117,185683049,185432814,62444370,150443703,1640919265
10,2021-11-01,195535051,217400617,147689950,44586510,93469521,177562948,40115118,76704600,81841121,183965811,181066575,58789117,145297494,1644024433
11,2021-12-01,173441716,198994259,143334763,49515931,97229769,158120587,40396961,67493171,77617610,172347874,184809368,56830182,143496539,1563628730
12,2022-01-01,173902081,200844040,159215340,50934810,98923830,166973297,39487525,69983116,79172261,183041258,185728043,55992092,139153276,1603350969
13,2022-02-01,169243045,183664073,178768506,50882748,114627203,165854520,36915981,72015636,75402829,170326406,164689463,57336436,133888101,1573614947
14,2022-03-01,184695751,196660177,186786924,47098103,118909097,166021168,41039215,71087858,74698558,175430145,159380947,53792590,144545277,1620145810
15,2022-04-01,199531458,232943210,179595494,47854612,115090499,199216837,39204308,83477911,87063045,200294158,180048001,60852371,155510497,1780682401
16,2022-05-01,205846346,243426759,152399328,44089913,98650890,207994288,33678006,83125885,89004131,203024065,197271984,61077304,162018217,1781607116
17,2022-06-01,225268513,296453092,151675736,45821674,98692154,238037275,33947047,93075247,105254582,223875686,186703797,70382710,185350014,1954537527
18,2022-07-01,223975070,302114730,150479215,42659220,98949287,236142364,33915240,92196207,109751551,233445367,195254898,74152874,188618574,1981654597
19,2022-08-01,219324309,303756047,148577723,45362393,96345256,227484949,38573831,91424519,110158224,231672958,200712772,74462738,189314786,1977170505
20,2022-09-01,220282463,298237762,169487049,55881942,106842652,224916166,42608718,93645587,105335207,219048697,198447610,74902017,173862340,1983498210
21,2022-10-01,205319852,278077938,144978237,51064158,102127134,216477350,40959586,81639051,89388406,197378689,178195641,67843691,152247198,1805696931
22,2022-11-01,193892466,238387870,152173396,56085317,103967415,202819821,42452820,82232417,78317781,200954983,186224647,60735187,164861048,1763105168
23,2022-12-01,188953287,238237420,160250539,54946562,106903956,186773918,46003139,74328607,82149136,194672756,177555622,60516914,148838468,1720130324
24,2023-01-01,151278934,198020079,146805744,53889420,105304740,175314182,37165631,65447813,69787181,159478872,152550110,52299987,124931855,1492274548
25,2023-02-01,177961166,214893731,181171306,56540322,127792773,189924549,44341187,75307632,78307702,182058583,176091725,60878115,143340887,1708609678
26,2023-03-01,176867768,226760150,203365421,66022917,128334530,184065794,43121854,70803450,78504209,187505156,160738906,55776102,145886111,1727752368
27,2023-04-01,201071762,263577819,199440776,65812059,130184998,227387246,41138185,86218995,87052560,207999642,171806536,63538594,171897527,1917126699
28,2023-05-01,216810167,286065814,187296839,60365365,117478037,247775311,38476870,92239501,94808312,218040740,200881892,66616139,175082939,2001937926
29,2023-06-01,228831703,330679786,168895712,53361487,107430058,271527719,36919148,96108003,110711603,227748124,195321222,76746089,195194018,2099474672
30,2023-07-01,233239947,326930522,157939171,53774306,99639058,257318544,35575725,98089406,113635119,235583294,208659512,76274477,198860925,2095520006
31,2023-08-01,242371738,343783477,163510885,56349981,102942041,265621102,41849276,102249857,110559224,240644513,215322023,76426513,199147336,2160777966
32,2023-09-01,245846739,334854205,176154962,54350765,110230293,260440322,43585903,100944943,99008566,236540705,205012048,77915611,178232208,2123117270
33,2023-10-01,229283628,325046776,177891988,55271575,104950394,268993300,45397486,107902396,89358961,216527628,191251580,69936919,174538640,2056351271
34,2023-11-01,237220530,306060760,181575737,65081029,123236212,245231088,46903748,81903276,92552312,225265298,188298784,78325276,166285061,2037939111
35,2023-12-01,209589687,251941410,192772258,68487295,129279584,220393105,53503395,91446014,76917535,198279228,177979839,69479002,168910328,1908978680
36,2024-01-01,217752375,245424572,187220071,76774275,175083206,209372461,52703106,80418680,89993245,230284016,174027218,60340117,143831781,1943225123
37,2024-02-01,192574920,207447504,197532396,70362781,146878983,196068026,42041468,75196236,70169936,169600044,161678291,55613670,127720682,1712884937
38,2024-03-01,226434785,284965616,255725535,79694103,160766425,235694577,53305738,91294032,86277063,218984921,195208922,65839829,163365520,2117557066
39,2024-04-01,244363691,308628213,254755130,76584240,166302227,263096083,49888676,101403567,104588279,233382499,221977075,72590240,186712681,2284272601
40,2024-05-01,260856946,338171599,222915053,69759755,132602652,287016154,43327721,106753144,107833547,260995710,238125119,79620384,197414563,2345392347
41,2024-06-01,260833989,370651778,192202350,58677511,122640070,287084140,41322242,105866124,122718500,261090273,231255978,84618179,209714426,2348675560
42,2024-07-01,255772368,340755894,175574535,51863903,101472322,287274057,37254149,105210301,115404015,256516607,219072794,82544968,201949922,2230665835

In [8]:
df_total = df_total.pivot_table(index='date',columns='PROVINCE',values='SLUONG_FINAL',aggfunc='sum')

KeyError: 'SLUONG_FINAL'

In [12]:
df_total = df_total.set_index('PHIEN')

In [14]:
df_datetime = pd.DataFrame({'stt': [i for i in range(df_total.shape[0])]},
                          index=df_total.sort_index(ascending=True).index)
df_datetime['month'] = df_datetime.index.month
df_datetime['year'] = df_datetime.index.year
df_datetime

            stt  month  year
PHIEN
2021-01-01    0      1  2021
2021-02-01    1      2  2021
2021-03-01    2      3  2021
2021-04-01    3      4  2021
2021-05-01    4      5  2021
2021-06-01    5      6  2021
2021-07-01    6      7  2021
2021-08-01    7      8  2021
2021-09-01    8      9  2021
2021-10-01    9     10  2021
2021-11-01   10     11  2021
2021-12-01   11     12  2021
2022-01-01   12      1  2022
2022-02-01   13      2  2022
2022-03-01   14      3  2022
2022-04-01   15      4  2022
2022-05-01   16      5  2022
2022-06-01   17      6  2022
2022-07-01   18      7  2022
2022-08-01   19      8  2022
2022-09-01   20      9  2022
2022-10-01   21     10  2022
2022-11-01   22     11  2022
2022-12-01   23     12  2022
2023-01-01   24      1  2023
2023-02-01   25      2  2023
2023-03-01   26      3  2023
2023-04-01   27      4  2023
2023-05-01   28      5  2023
2023-06-01   29      6  2023
2023-07-01   30      7  2023
2023-08-01   31      8  2023
2023-09-01   32      9  2023
2023-10-01   33     10  2023
2023-11-01   34     11  2023
2023-12-01   35     12  2023
2024-01-01   36      1  2024
2024-02-01   37      2  2024
2024-03-01   38      3  2024
2024-04-01   39      4  2024
2024-05-01   40      5  2024
2024-06-01   41      6  2024
2024-07-01   42      7  2024

In [15]:
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.seasonal import STL
from prophet import Prophet
import pandas as pd
from pmdarima import auto_arima


def measure_simility(arr1, arr2):
    arr1 = arr1.reshape((-1,))
    arr2 = arr2.reshape((-1,))
    score = np.corrcoef(arr1, arr2)[0, 1]
    return score


def pick_data_train(vt, arrs, n):
    score = []
    for arr in arrs:
        score.append(measure_simility(vt, arr))
    score = np.array(score)
    return np.argsort(score)[-n:], score[np.argsort(score)[-n:]]


def create_data_total(df, month, year, lag, shift):
    x_knowns = df[df.index < year].iloc[:, 11 + month - lag - shift: 11 + month - shift].values.reshape((-1, lag))
    # y_known = df[df.index == year].iloc[0,11 + month-lag: 11 +month].values
    y_known = df[df.index == year].iloc[0, 11 + month - lag: 11 + month].values
    # y_known = df.iloc[-1, 11 + month - lag: 11 + month].values
    x_news = df[df.index < year].iloc[:, 11 + month - shift].values
    # print(month,year,y_known)
    return x_knowns, y_known, x_news


def create_data_cumsum(df, month, year, lag, shift):
    x_knowns = df[df.index < year].iloc[:, 11 + month - lag - shift: 11 + month - shift].cumsum(axis=1).values.reshape(
        (-1, lag))
    y_known = df[df.index == year].iloc[:, 11 + month - lag: 11 + month].cumsum(axis=1).iloc[0, :].values
    # y_known = df.iloc[[-1], 11 + month - lag: 11 + month].cumsum(axis=1).iloc[0, :].values
    x_news = df[df.index < year].iloc[:, 11 + month - lag - shift: 12 + month - shift].cumsum(axis=1).iloc[:, -1].values
    return x_knowns, y_known, x_news


def create_data_rolling(df, month, year, lag, shift, n_rolling):
    y_old = df[df.index == year].iloc[0, 11 + month - 1 - n_rolling + 1:11 + month - 1].sum()
    df = df.rolling(n_rolling, axis=1).mean()
    x_knowns = df[df.index < year].iloc[:, 11 + month - lag - shift: 11 + month - shift].values.reshape((-1, lag))
    y_known = df[df.index == year].iloc[0, 11 + month - lag: 11 + month].values
    x_news = df[df.index < year].iloc[:, 11 + month - shift].values
    return x_knowns, y_known, x_news, y_old


def predict_total(known_y, known_x, new_x, order):
    # known_y = known_y.reshape((-1,))
    # known_x = known_x.reshape((-1,))
    coefficients = np.polyfit(known_x, known_y, order)
    estimated_func = np.poly1d(coefficients)
    return float(estimated_func(new_x))


def predict_cumsum(known_y, known_x, new_x, order):
    # known_y = known_y.reshape((-1,))
    # known_x = known_x.reshape((-1,))
    coefficients = np.polyfit(known_x, known_y, order)
    estimated_func = np.poly1d(coefficients)
    return float(estimated_func(new_x))


def predict(df_total, year, month: int, lag: int, order1: int, order2: int, shift: int, n_max):
    x_knowns, y_known, x_news = create_data_total(df_total, month, year, lag, shift)
    max_scores, coeffs = pick_data_train(y_known, x_knowns, n_max)
    pre = []
    for max_score in max_scores:
        x_knowns, y_known, x_news = create_data_total(df_total, month, year, lag, shift)
        x_known = x_knowns[max_score]
        x_new = x_news[max_score]

        pred1 = predict_total(known_y=y_known,
                              known_x=x_known,
                              new_x=x_new, order=order1)
        pre.append(pred1)
        shift = 0
        x_knowns, y_known, x_news = create_data_cumsum(df_total, month, year, lag, shift)
        x_known = x_knowns[max_score]
        x_new = x_news[max_score]
        pred2 = predict_cumsum(known_y=y_known,
                               known_x=x_known,
                               new_x=x_new, order=order2) - y_known[-1]

        pre.append(pred2)
    return np.mean(pre), coeffs.mean()


def predict_master(data: pd.DataFrame, d_date: pd.DataFrame, month, year, lag, p, d, q, n_max, type_decomp,
                   methods_season, method_resid, method_trend, order1, order2):
    date = f"{year}-{month}-1"
    # print(date)
    # d_train = data[data.index < f"{year}-1-1"]
    d_train = data[data.index < date]
    d_train = pd.concat([d_train, d_date], axis=1).dropna(axis=0)

    d_residuals, d_trend, d_seasonal = detrend(d_train, type=type_decomp)
    # y_residual=0
    y_residual = forecast_residual(d_residuals.values, p, d, q, method_resid=method_resid)
    # except:
    #     y_residual = 0

    d_seasonal.name = name_province
    # d_seasonal = pd.concat([d_seasonal, d_date], axis=1)
    d_seasonal = pd.concat([d_seasonal, d_date], axis=1).fillna(0)
    d_seasonal = d_seasonal.pivot_table(columns='month', index='year', values=name_province)
    y_seasonal = forecast_seasonal(d_seasonal, month, year, lag, n_max, order1, order2, methods_season)

    d_trend.name = name_province
    d_trend = pd.concat([d_trend, d_date], axis=1).dropna()
    y_trend = forecast_trend(d_trend.iloc[-2, 0], d_trend.iloc[-1, 0], method_trend=method_trend)

    # d_residuals = pd.concat([d_residuals, d_date], axis=1).dropna()
    # y_re3 = d_seasonal.pivot_table(columns='month', index='year', values=name_province).dropna(axis=0).mean(axis=0)[
    #     month]
    # d_residuals = d_residuals.pivot_table(columns='month', index='year', values=name_province)
    # d_trend = d_trend.pivot_table(columns='month', index='year', values=name_province)
    # y_re2 = forecast_seasonal(d_trend, month, year, lag, 2)
    # return y_lr + (y_re1 +y_re2+y_re)/3,y_re
    # return (y_re3 + y_re1) / 2 + y_re2
    return y_trend, y_seasonal, y_residual


def detrend(df: pd.DataFrame, type='STL'):
    if type == 'STL':
        data = df.copy()
        data = data.iloc[:, 0]
        stl = STL(data, period=12)
        res = stl.fit()
        trend = res.trend
        resid = res.resid
        season = res.seasonal
        return resid, trend, season
    if type == 'prophet':
        data = df.copy()
        data = data.iloc[:, [0]]
        data = data.reset_index()
        data.columns = ['ds', 'y']
        model = Prophet(yearly_seasonality=12)
        model.fit(data)
        forecaster = model.predict(model.make_future_dataframe(periods=0, freq='MS'))
        forecaster['y'] = data['y']
        forecaster['resid'] = forecaster.apply(lambda row: (row.y - (row.yearly + row.trend)), axis=1)
        forecaster = forecaster.set_index('ds')
        df_resid = forecaster['resid']
        df_trend = forecaster['trend']
        df_season = forecaster['yearly']
        df_season.name = 'seasonal'
        return df_resid, df_trend, df_season
    else:
        return None, None, None


def compute_error(data, month, year, y_pr):
    y_tr = data[data.index == f'{year}-{month}-1'].values[0]
    return (y_pr - y_tr) / y_tr, y_tr


def forecast_seasonal(data, month, year, lag, n_max, order1, order2, method='statistics'):
    if method == 'statistics':
        df = data.copy()
        df = pd.concat([df.shift(1, axis=0), df, df.shift(-1, axis=0)], axis=1).iloc[1:, :] + 10e10
        # lag = int(params[month - 1][1])
        # shift = int(params[month - 1][2])
        # order1 = int(params[month - 1][3])
        # order2 = int(params[month - 1][4])
        # lag = 6
        shift = 0
        # order1 = 1
        # order2 = 1
        y, _ = predict(df, year, month, lag, order1, order2, shift, n_max)
        return y - 10e10
    if method == 'average':
        df = data.copy()
        # df = df[df.index<year]
        # print(df.dropna(axis=0).mean(axis=0))
        y = df.dropna(axis=0).mean(axis=0)[month]
        # print(y)
        return y
    if method == 'latest':
        df = data.copy()
        # df = df[df.index<year]
        # print(df.dropna(axis=0).mean(axis=0))
        y = df.dropna(axis=0).iloc[-1, :][month]
        # print(y)
        return y
    else:
        raise "Not specify the season method"


def forecast_trend(y_1, y_t, method_trend='average'):
    if method_trend == 'average':
        y_pr_trend = y_t + (y_t - y_1)
        # y_pr_trend = y_t
        return y_pr_trend
    if method_trend == 'latest':
        return y_t
    else:
        raise "Not specify the trend method"


def forecast_residual(series, p, d, q, method_resid='arima'):
    if method_resid == 'arima':
        try:
            model = ARIMA(series, order=(p, d, q))
            model_fit = model.fit()
            return model_fit.forecast(freq='MS')[0]
        except:
            return 0
    # if method_resid == 'autoarima':
    #     model = auto_arima(series, seasonal=False, trace=False)
    #     return model.predict(n_periods=1, freq='MS')[0]
    else:
        return 0


def get_ytr(df, month, year):
    try:
        filter = f'{year}-{month}-01'
        return df[df.index == filter].values[0][0]
    except:
        return None

In [16]:
df_total

,BDINH,DANANG,DLAC,DNONG,GLAI,KHOA,KTUM,PYEN,QBINH,QNAM,QNGAI,QTRI,TTHUE,TOTAL
PHIEN,,,,,,,,,,,,,,
2021-01-01,172740120,203601803,147457074,44596327,90428875,154108940,41738931,64427738,75663066,157055696,174093766,54194223,128704328,1508810887
2021-02-01,144247290,180774297,147913340,48214165,106511589,146572064,34211284,62135056,72019515,140222204,150764661,48705202,117046364,1399337031
2021-03-01,181550824,194145612,186440175,48782238,108250474,152211725,38802307,70020661,73264978,154367593,159436181,50696210,129905222,1547874200
2021-04-01,199746953,238971267,206295423,52172946,124368219,192014064,37639153,84095864,85638321,192248075,183784444,58072285,149330895,1804377909
2021-05-01,204394644,245267546,176763006,43851699,100472859,197897822,32011523,86273178,88530983,196539440,183387482,61960664,161610697,1778961543
2021-06-01,228505885,266731131,142944656,46174071,101666699,211777539,33170708,92921191,107204687,217478486,218354068,71719111,178211205,1916859437
2021-07-01,221138117,270969071,151337167,41506884,91817473,198623691,32665248,85375068,105889038,220382599,208500094,71489061,176280231,1875973742
2021-08-01,219844509,261542900,138773834,42523878,87648926,195990592,36277376,89138509,107068894,217134381,244827558,71962232,184218767,1896952356
2021-09-01,198720930,215147407,143631179,44390920,91234608,177671416,39612071,85693213,92221686,191223040,184386773,68179220,162030947,1694143410
2021-10-01,195872288,214121072,145116628,38845340,88811751,173821507,37360942,80852684,82113117,185683049,185432814,62444370,150443703,1640919265
2021-11-01,195535051,217400617,147689950,44586510,93469521,177562948,40115118,76704600,81841121,183965811,181066575,58789117,145297494,1644024433
2021-12-01,173441716,198994259,143334763,49515931,97229769,158120587,40396961,67493171,77617610,172347874,184809368,56830182,143496539,1563628730
2022-01-01,173902081,200844040,159215340,50934810,98923830,166973297,39487525,69983116,79172261,183041258,185728043,55992092,139153276,1603350969
2022-02-01,169243045,183664073,178768506,50882748,114627203,165854520,36915981,72015636,75402829,170326406,164689463,57336436,133888101,1573614947
2022-03-01,184695751,196660177,186786924,47098103,118909097,166021168,41039215,71087858,74698558,175430145,159380947,53792590,144545277,1620145810
2022-04-01,199531458,232943210,179595494,47854612,115090499,199216837,39204308,83477911,87063045,200294158,180048001,60852371,155510497,1780682401
2022-05-01,205846346,243426759,152399328,44089913,98650890,207994288,33678006,83125885,89004131,203024065,197271984,61077304,162018217,1781607116
2022-06-01,225268513,296453092,151675736,45821674,98692154,238037275,33947047,93075247,105254582,223875686,186703797,70382710,185350014,1954537527
2022-07-01,223975070,302114730,150479215,42659220,98949287,236142364,33915240,92196207,109751551,233445367,195254898,74152874,188618574,1981654597
2022-08-01,219324309,303756047,148577723,45362393,96345256,227484949,38573831,91424519,110158224,231672958,200712772,74462738,189314786,1977170505
2022-09-01,220282463,298237762,169487049,55881942,106842652,224916166,42608718,93645587,105335207,219048697,198447610,74902017,173862340,1983498210
2022-10-01,205319852,278077938,144978237,51064158,102127134,216477350,40959586,81639051,89388406,197378689,178195641,67843691,152247198,1805696931
2022-11-01,193892466,238387870,152173396,56085317,103967415,202819821,42452820,82232417,78317781,200954983,186224647,60735187,164861048,1763105168
2022-12-01,188953287,238237420,160250539,54946562,106903956,186773918,46003139,74328607,82149136,194672756,177555622,60516914,148838468,1720130324
2023-01-01,151278934,198020079,146805744,53889420,105304740,175314182,37165631,65447813,69787181,159478872,152550110,52299987,124931855,1492274548
2023-02-01,177961166,214893731,181171306,56540322,127792773,189924549,44341187,75307632,78307702,182058583,176091725,60878115,143340887,1708609678
2023-03-01,176867768,226760150,203365421,66022917,128334530,184065794,43121854,70803450,78504209,187505156,160738906,55776102,145886111,1727752368
2023-04-01,201071762,263577819,199440776,65812059,130184998,227387246,41138185,86218995,87052560,207999642,171806536,63538594,171897527,1917126699
2023-05-01,216810167,286065814,187296839,60365365,117478037,247775311,38476870,92239501,94808312,218040740,200881892,66616139,175082939,2001937926
2023-06-01,228831703,330679786,168895712,53361487,107430058,271527719,36919148,96108003,110711603,227748124,195321222,76746089,195194018,2099474672
2023-07-01,233239947,326930522,157939171,53774306,99639058,257318544,35575725,98089406,113635119,235583294,208659512,76274477,198860925,2095520006
2023-08-01,242371738,343783477,163510885,56349981,102942041,265621102,41849276,102249857,110559224,240644513,215322023,76426513,199147336,2160777966
2023-09-01,245846739,334854205,176154962,54350765,110230293,260440322,43585903,100944943,99008566,236540705,205012048,77915611,178232208,2123117270
2023-10-01,229283628,325046776,177891988,55271575,104950394,268993300,45397486,107902396,89358961,216527628,191251580,69936919,174538640,2056351271
2023-11-01,237220530,306060760,181575737,65081029,123236212,245231088,46903748,81903276,92552312,225265298,188298784,78325276,166285061,2037939111
2023-12-01,209589687,251941410,192772258,68487295,129279584,220393105,53503395,91446014,76917535,198279228,177979839,69479002,168910328,1908978680
2024-01-01,217752375,245424572,187220071,76774275,175083206,209372461,52703106,80418680,89993245,230284016,174027218,60340117,143831781,1943225123
2024-02-01,192574920,207447504,197532396,70362781,146878983,196068026,42041468,75196236,70169936,169600044,161678291,55613670,127720682,1712884937
2024-03-01,226434785,284965616,255725535,79694103,160766425,235694577,53305738,91294032,86277063,218984921,195208922,65839829,163365520,2117557066
2024-04-01,244363691,308628213,254755130,76584240,166302227,263096083,49888676,101403567,104588279,233382499,221977075,72590240,186712681,2284272601
2024-05-01,260856946,338171599,222915053,69759755,132602652,287016154,43327721,106753144,107833547,260995710,238125119,79620384,197414563,2345392347
2024-06-01,260833989,370651778,192202350,58677511,122640070,287084140,41322242,105866124,122718500,261090273,231255978,84618179,209714426,2348675560
2024-07-01,255772368,340755894,175574535,51863903,101472322,287274057,37254149,105210301,115404015,256516607,219072794,82544968,201949922,2230665835

In [ ]:
# lst_pr = df_total.columns[:-2]
lst_pr = df_total.columns
from tqdm import trange, tqdm

df_parameters = pd.DataFrame()
years = [2022,2023]
lst_nmax = [ 2,5,10]
lst_decomps = ['STL',]
lst_method_season = ['statistics',]
lst_method_resid = ['arima', 'None']
lst_method_trend = ['average',]
lst_order1 = [1]
lst_order2 = [1]
# try:
for n_max in tqdm(lst_nmax):
    for n_province in trange(13):
        df = df_total.iloc[:, [n_province]]
        name_province = lst_pr[n_province]
        df = df.sort_index()
        # print(name_province)
        for year in years:
            for lag in [6, 8, 10]:
                for order1 in lst_order1:
                    for order2 in lst_order2:
                        for month in range(1, 13):
                            # try:
                            p = 1
                            d = 0
                            q = 1
                            for decomp in lst_decomps:
                                for method_season in lst_method_season:
                                    for method_resid in lst_method_resid:
                                        for method_trend in lst_method_trend:
                                            y_trend, y_seasonal, y_residual = predict_master(
                                                data=df,
                                                d_date=df_datetime,
                                                month=month, year=year,
                                                lag=lag, p=p, d=d, q=q,
                                                n_max=n_max,
                                                type_decomp=decomp,
                                                methods_season=method_season, method_resid=method_resid,
                                                method_trend=method_trend, order1=order1,
                                                order2=order2)

                                            y_pr = y_trend + y_seasonal + y_residual
                                            # try:
                                            error, y_tr = compute_error(df, month, year, y_pr)
                                            df_parameters = pd.concat([df_parameters, pd.DataFrame(
                                                {'n_max': n_max,
                                                 'province': name_province,
                                                 'year': year,
                                                 'month': month,
                                                 'y_pr': y_pr,
                                                 'y_tr': y_tr,
                                                 'error': error,
                                                 'error_abs': np.abs(error),
                                                 'y_trend': y_trend,
                                                 'y_seasonal': y_seasonal,
                                                 'y_residual': y_residual,
                                                 'lag': lag,
                                                 'p': p, 'd': d, 'q': q,
                                                 'type_decomp': decomp,
                                                 'method_season': method_season,
                                                 'method_resid': method_resid,
                                                 'method_trend': method_trend,
                                                 'order1': order1,
                                                 'order2': order2
                                                 })])
                        # except:
                        #     break

        # except: pass

  0%|          | 0/3 [00:00<?, ?it/s]
  0%|          | 0/13 [00:00<?, ?it/s]
  8%|▊         | 1/13 [00:07<01:29,  7.48s/it]
 15%|█▌        | 2/13 [00:16<01:29,  8.13s/it]

In [11]:
df_parameters

,n_max,province,year,month,y_pr,y_tr,error,error_abs,y_trend,y_seasonal,...,lag,p,d,q,type_decomp,method_season,method_resid,method_trend,order1,order2
0,2,BDINH,2022,1,5.882589e+07,58135306,0.011879,0.011879,5.886699e+07,1.555094e+04,...,6,1,0,1,STL,statistics,arima,average,1,1
0,2,BDINH,2022,1,5.888254e+07,58135306,0.012853,0.012853,5.886699e+07,1.555094e+04,...,6,1,0,1,STL,statistics,None,average,1,1
0,2,BDINH,2022,2,4.820441e+07,48938665,-0.015004,0.015004,5.914862e+07,-1.089325e+07,...,6,1,0,1,STL,statistics,arima,average,1,1
0,2,BDINH,2022,2,4.825537e+07,48938665,-0.013962,0.013962,5.914862e+07,-1.089325e+07,...,6,1,0,1,STL,statistics,None,average,1,1
0,2,BDINH,2022,3,6.402526e+07,67827147,-0.056053,0.056053,6.000894e+07,4.229072e+06,...,6,1,0,1,STL,statistics,arima,average,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,10,TTHUE,2023,10,4.923900e+07,52643747,-0.064675,0.064675,4.887365e+07,3.653478e+05,...,10,1,0,1,STL,statistics,None,average,1,1
0,10,TTHUE,2023,11,5.273785e+07,48759521,0.081591,0.081591,5.000955e+07,2.678485e+06,...,10,1,0,1,STL,statistics,arima,average,1,1
0,10,TTHUE,2023,11,5.268803e+07,48759521,0.080569,0.080569,5.000955e+07,2.678485e+06,...,10,1,0,1,STL,statistics,None,average,1,1
0,10,TTHUE,2023,12,4.969115e+07,51019237,-0.026031,0.026031,4.873522e+07,1.116131e+06,...,10,1,0,1,STL,statistics,arima,average,1,1
0,10,TTHUE,2023,12,4.985135e+07,51019237,-0.022891,0.022891,4.873522e+07,1.116131e+06,...,10,1,0,1,STL,statistics,None,average,1,1

In [11]:
# df_parameters.to_parquet('/path/to/company_data/user/<user>/cpc/data/parameter/df_parameter_u2022.parquet',index=False,filesystem= hdfs)

In [14]:
dfp = df_parameters.groupby(['province','n_max','lag','type_decomp','method_season','method_resid','method_trend']).agg({'error_abs':'mean'}).reset_index().groupby(['province']).apply(
    lambda x: x[x.error_abs <= x.error_abs.nsmallest(1).iloc[-1]]).drop_duplicates('error_abs').reset_index(drop=True)
dfp

,province,n_max,lag,type_decomp,method_season,method_resid,method_trend,error_abs
0,BDINH,10,6,STL,statistics,None,average,0.081362
1,DANANG,10,6,STL,statistics,arima,average,0.066686
2,DLAC,10,6,STL,statistics,arima,average,0.198305
3,DNONG,5,6,STL,statistics,arima,average,0.246375
4,GLAI,5,8,STL,statistics,None,average,0.144923
5,KHOA,5,6,STL,statistics,arima,average,0.089738
6,KTUM,2,10,STL,statistics,None,average,0.128623
7,PYEN,5,6,STL,statistics,None,average,0.144254
8,QBINH,2,8,STL,statistics,None,average,0.141760
9,QNAM,10,6,STL,statistics,arima,average,0.066424
10,QNGAI,10,6,STL,statistics,arima,average,0.101527
11,QTRI,5,8,STL,statistics,None,average,0.130764
12,TTHUE,10,10,STL,statistics,None,average,0.058410

In [15]:
dfp.to_parquet('/path/to/company_data/user/<user>/cpc/data/parameter/final_params_13province_u2023.parquet',index=False,filesystem= hdfs)

In [34]:
from tqdm import trange
lst_pr = df_total.columns[:-2]

df_result = pd.DataFrame()
years = [2022,2023]

for n_province in trange(13):
    df = df_total.iloc[:, [n_province]]
    name_province = lst_pr[n_province]
    df = df.sort_index()
    dp = dfp[dfp.province ==name_province]
    lag = 6
    n_max = dp.n_max.values[0]
    # type_decomp = dp.type_decomp.values[0]
    type_decomp = 'STL'
    method_season =dp.method_season.values[0]
    method_trend =dp.method_trend.values[0]
    method_resid =dp.method_resid.values[0]
    p = 1
    d = 0
    q = 1
    # print(name_province)
    for year in years:
        for month in range(1, 13):
            # print(month)
            y_trend, y_seasonal, y_residual = predict_master(
                data=df,
                d_date=df_datetime,
                month=month, year=year,
                lag=lag, p=p, d=d, q=q,
                n_max=n_max,
                type_decomp=type_decomp,
                methods_season=method_season, method_resid=method_resid,
                method_trend=method_trend,order1=1,
                order2=1)

            y_pr = y_trend + y_seasonal + y_residual
            try:
                error, y_tr = compute_error(df, month, year, y_pr)
                df_result = pd.concat([df_result, pd.DataFrame(
                    {'n_max': n_max,
                     'province': name_province,
                     'year': year,
                     'month': month,
                     'y_pr': y_pr,
                     'y_tr': y_tr,
                     'error': error,
                     'error_abs': np.abs(error),
                     'y_trend': y_trend,
                     'y_seasonal': y_seasonal,
                     'y_residual': y_residual,
                     'lag': lag,
                     'p': p, 'd': d, 'q': q,
                     'type_decomp': type_decomp,
                     'method_season': method_season,
                     'method_resid': method_resid,
                     'method_trend': method_trend,
                     })])
            except:
                df_result = pd.concat([df_result, pd.DataFrame(
                    {'n_max': n_max,
                     'province': name_province,
                     'year': year,
                     'month': month,
                     'y_pr': y_pr,
                     'y_tr': [None],
                     'error': [None],
                     'error_abs': [None],
                     'y_trend': y_trend,
                     'y_seasonal': y_seasonal,
                     'y_residual': y_residual,
                     'lag': lag,
                     'p': p, 'd': d, 'q': q,
                     'type_decomp': type_decomp,
                     'method_season': method_season,
                     'method_resid': method_resid,
                     'method_trend': method_trend,
                     })])
                break

100%|██████████| 13/13 [00:08<00:00,  1.46it/s]

In [35]:
df_result.pivot_table(index='province',columns=['year','month'],values='error')

year          2022                                                    \
month           1         2         3         4         5         6
province
BDINH     0.011142 -0.051929 -0.006832 -0.013375 -0.004660 -0.001401
DANANG   -0.053807 -0.066730 -0.026577 -0.080983 -0.048843 -0.073017
DLAC     -0.097120 -0.076442  0.048028  0.128727  0.170148  0.004444
DNONG    -0.040378 -0.027311  0.042492 -0.006172  0.042989 -0.003316
GLAI      0.008802 -0.043470 -0.038006  0.062523  0.049552  0.013721
KHOA     -0.097344 -0.106003 -0.056245 -0.080269 -0.033439 -0.062262
KTUM      0.048301 -0.009015 -0.030981  0.016744  0.009416  0.028481
PYEN     -0.021467 -0.051485  0.050695  0.040281  0.047997  0.005669
QBINH    -0.070960 -0.004216  0.022941 -0.006924  0.013175  0.033354
QNAM     -0.069462 -0.078092  0.013658 -0.001251  0.024116  0.030275
QNGAI     0.012061  0.058814  0.141872  0.082246 -0.014236  0.134860
QTRI      0.004796 -0.048828  0.030616  0.000561  0.016704  0.012647
TTHUE    -0.035273 -0.054849 -0.000617  0.000396  0.024232 -0.025986

year                                                                  \
month           7         8         9         10        11        12
province
BDINH    -0.011415  0.006010 -0.030709 -0.012047  0.000484 -0.033125
DANANG   -0.036425 -0.068859 -0.067789 -0.012735  0.084353 -0.009312
DLAC     -0.032968 -0.060638 -0.130126 -0.015625 -0.005683 -0.037906
DNONG     0.055246  0.004617 -0.175206 -0.035273 -0.079860 -0.027856
GLAI     -0.094119 -0.045207 -0.115492 -0.057961 -0.005824  0.018192
KHOA     -0.064978  0.013117  0.001986  0.013288  0.036989  0.009882
KTUM     -0.029548 -0.076449 -0.045953 -0.033628  0.002278 -0.056864
PYEN     -0.052788 -0.014424 -0.033490  0.002789 -0.056911 -0.025871
QBINH    -0.025452 -0.035831 -0.063913 -0.025582  0.087934 -0.001648
QNAM     -0.011572 -0.025233 -0.020714  0.054365 -0.062875 -0.019910
QNGAI    -0.000945  0.010767 -0.027342  0.029618 -0.066805 -0.032245
QTRI     -0.028028 -0.026181 -0.083660 -0.059905 -0.015896  0.023382
TTHUE    -0.043124 -0.031089  0.005860  0.047577 -0.063470  0.043334

year          2023                                                    \
month           1         2         3         4         5         6
province
BDINH     0.180036 -0.052829  0.060770 -0.004531 -0.063717 -0.009214
DANANG    0.230952 -0.024879  0.045900 -0.016914 -0.053396 -0.015306
DLAC      0.063607 -0.020677 -0.014733  0.022173 -0.025390  0.009980
DNONG     0.053425  0.018597 -0.137453 -0.058244 -0.038183  0.148973
GLAI      0.051638 -0.066388 -0.017347  0.003860 -0.015739  0.067398
KHOA      0.089903 -0.042407  0.033283 -0.039527 -0.069087 -0.044341
KTUM      0.174860 -0.092311  0.015526  0.033201 -0.043902  0.029327
PYEN      0.122992 -0.020852  0.061739  0.031136 -0.050974  0.010619
QBINH     0.164313 -0.026758 -0.035067  0.013090 -0.050699 -0.008090
QNAM      0.219544 -0.057783 -0.014285 -0.013002 -0.034318  0.024690
QNGAI     0.131589 -0.102327  0.038667  0.045524 -0.072376  0.012922
QTRI      0.112581 -0.063948  0.019264 -0.017692 -0.048389 -0.021973
TTHUE     0.145183 -0.084643  0.010924 -0.083327 -0.037213 -0.023238

year
month           7         8
province
BDINH    -0.028541 -0.066573
DANANG    0.015979 -0.055320
DLAC      0.049186 -0.031593
DNONG     0.025216  0.038453
GLAI      0.060063 -0.000445
KHOA     -0.005471 -0.025767
KTUM      0.051290 -0.022245
PYEN     -0.051514 -0.074220
QBINH    -0.045792  0.004307
QNAM      0.001956 -0.031951
QNGAI    -0.074280 -0.055287
QTRI      0.003994 -0.005262
TTHUE    -0.033002 -0.023263

In [37]:
df_result.groupby(['province']).agg({'error_abs':'mean'})

          error_abs
province
BDINH      0.032467
DANANG     0.054404
DLAC       0.052260
DNONG      0.052963
GLAI       0.041787
KHOA       0.046279
KTUM       0.042516
PYEN       0.041396
QBINH      0.037002
QNAM       0.040453
QNGAI      0.057239
QTRI       0.032215
TTHUE      0.040830